### PR TITLE
Add CMake to Linux based images

### PR DESCRIPTION
**Pull request by dbrgn**
I already tested the build with those images: https://dev.azure.com/LibrePCB/LibrePCB/_build/results?buildId=1465&view=results

### CODE REVIEW

**Review by ubruhin — APPROVED** [review]
:+1:

**Comment by dbrgn** [comment]
@ubruhin can you publish new tags?

**Comment by ubruhin** [comment]
> @ubruhin can you publish new tags?

Will do, but first I'll update some images to the latest Qt version as well to avoid an additional iteration ;)

**Comment by dbrgn** [comment]
Just saying: If we'd upload the images through CI on every push (and not manually), we'd save a lot of effort.

**Pull request merged**
