### PR TITLE
Add Debian 8 (jessie) based container

### PR DESCRIPTION
**Pull request by rnestler**

### CODE REVIEW

**Comment by rnestler** [comment]
@ubruhin I tested locally if I can build LibrePCB. Building it works, but I'm not sure how to verify if CI would run though.

**Comment by ubruhin** [comment]
You would have to upload the image somewhere (e.g. to the personal account of Docker Hub or GitLab.com) and open a PR on the LibrePCB repository using that image.

Btw, don't forget to update the README.md :)

**Comment by rnestler** [comment]
Tested in https://github.com/LibrePCB/LibrePCB/pull/480.

**Comment by dbrgn** [comment]
I assume you're using an outdated distro version on purpose, right?

**Comment by rnestler** [comment]
> I assume you're using an outdated distro version on purpose, right?

Yes, @ubruhin  loves backwards compatibility and Jessie is still supported :slightly_smiling_face: . It is supposed to replace Ubuntu 14.04.

**Comment by rnestler** [comment]
> Btw, don't forget to update the README.md :)

Done.

**Comment by rnestler** [comment]
Ping @ubruhin

**Comment by ubruhin** [comment]
Well, IMHO it would have made more sense to close this since https://github.com/LibrePCB/LibrePCB/pull/480 has been closed too so we don't need this image... Now we have an ugly (non-linear) history here because the branch was outdated for many months :(

**Comment by rnestler** [comment]
> Well, IMHO it would have made more sense to close this since LibrePCB/LibrePCB#480 has been closed too so we don't need this image... Now we have an ugly (non-linear) history here because the branch was outdated for many months :(

Ah sorry, I just went through old open pull requests and saw it was approved and just merged it without looking at the date...

**Pull request merged**
